# Generated by Django 5.0.3 on 2025-07-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycleimage',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
