# Generated by Django 5.0.3 on 2025-07-23 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GarageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agde Moto Gattuso', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('social_media_json', models.TextField(default='{"facebook": "", "instagram": "", "youtube": "", "twitter": "", "linkedin": ""}')),
                ('business_hours_json', models.TextField(default='{"monday": {"open": "09:00", "close": "18:00", "is_closed": false}, "tuesday": {"open": "09:00", "close": "18:00", "is_closed": false}, "wednesday": {"open": "09:00", "close": "18:00", "is_closed": false}, "thursday": {"open": "09:00", "close": "18:00", "is_closed": false}, "friday": {"open": "09:00", "close": "18:00", "is_closed": false}, "saturday": {"open": "09:00", "close": "17:00", "is_closed": false}, "sunday": {"open": "10:00", "close": "16:00", "is_closed": true}}')),
                ('seo_settings_json', models.TextField(default='{"meta_title": "", "meta_description": "", "meta_keywords": "", "og_title": "", "og_description": "", "og_image": ""}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres du garage',
                'verbose_name_plural': 'Paramètres du garage',
            },
        ),
    ]
