# Generated by Django 5.0.3 on 2025-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garagesettings',
            name='business_hours_json',
            field=models.TextField(default='{"monday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "18:00"}]}, "tuesday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "18:00"}]}, "wednesday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "18:00"}]}, "thursday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "18:00"}]}, "friday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "18:00"}]}, "saturday": {"is_closed": false, "intervals": [{"open": "09:00", "close": "17:00"}]}, "sunday": {"is_closed": true, "intervals": []}}'),
        ),
    ]
